import fs from "node:fs";
import { registerWorkflowRoutes, type WorkflowHttpService } from "./routes/workflow-runs.js";
import express from "express";
import path from "node:path";
import { z } from "zod";
import { CreatorResearchService } from "../core/creator-research-service.js";
import { ComparisonProjectService, type CreatorResearchBatchService } from "../../packages/research/index.js";
import { PublishingService } from "../../packages/creation/index.js";
import {
  builderIntegrityContractRevision,
  evidenceResearchRoot,
  projectRoot,
  runtimeDir
} from "../../packages/adapters/index.js";
import { createCreatorResearchRunInputSchema, discoverCreatorsInputSchema } from "../shared/schema.js";
import { defaultAiCreatorKeywords, RedFoxCreatorDiscoveryService } from "../../packages/adapters/index.js";
import { loadCreatorSummaries } from "./creators.js";
import { loadCreatorDossier } from "./creator-dossier.js";
import { listLatestVideoResearch, loadVideoResearch } from "./video-research.js";
import { loadComparisonDossier } from "./comparison-dossier.js";
import type { ResearchLearningService } from "./research-learning.js";
import type { ContentKnowledgeService } from "../../packages/knowledge/index.js";
import type { LearningLoopControlPlane } from "./learning-loop.js";
import { registerPublishingRoutes } from "./routes/publishing.js";
import { registerKnowledgeRoutes } from "./routes/knowledge.js";
import { registerKnowledgeActivationRoutes } from "./routes/knowledge-activation.js";
import { KnowledgeActivationService } from "./knowledge-activation.js";
import { registerLearningLoopRoutes } from "./routes/learning-loop.js";
import { registerEvidenceRoutes } from "./routes/evidence.js";
import { registerWorkspaceRoutes } from "./routes/workspace.js";
import { registerCreatorResearchBatchRoutes } from "./routes/creator-research-batches.js";
import { ingestAnalysisRevisionSchema, type EvidenceAccessPort } from "../../packages/contracts/index.js";
import { buildCreatorRunOperations } from "./creator-operations.js";

export interface AppDependencies {
  workflows?: WorkflowHttpService;
  creatorResearch: CreatorResearchService;
  creatorResearchBatches?: CreatorResearchBatchService;
  comparisons: ComparisonProjectService;
  researchLearning: ResearchLearningService;
  learningLoop: LearningLoopControlPlane;
  publishing: PublishingService;
  creatorDiscovery: RedFoxCreatorDiscoveryService;
  contentKnowledge: ContentKnowledgeService;
  evidence: EvidenceAccessPort;
}

export function registerSpaFallback(app: express.Express, clientDirectory: string): void {
  if (!fs.existsSync(path.join(clientDirectory, "index.html"))) return;
  app.use(express.static(clientDirectory, {
    setHeaders: (response, filePath) => {
      // SPA entry must never be cached — stale bundles show outdated pages.
      if (filePath.endsWith("index.html")) response.setHeader("Cache-Control", "no-cache");
    }
  }));
  app.use((request, response, next) => {
    if (request.method === "GET" && !request.path.startsWith("/api") && !request.path.startsWith("/artifacts")) {
      response.setHeader("Cache-Control", "no-cache");
      // A relative filename avoids sendFile's dotfile check on hidden ancestors
      // such as a Codex worktree rooted beneath .codex.
      return response.sendFile("index.html", { root: clientDirectory });
    }
    return next();
  });
}

export function createApp({
  workflows,
  creatorResearch: creatorResearchService,
  creatorResearchBatches: creatorResearchBatchService,
  comparisons: comparisonProjectService,
  researchLearning: researchLearningService,
  learningLoop: learningLoopControlPlane,
  publishing: publishingService,
  creatorDiscovery: creatorDiscoveryService,
  contentKnowledge: contentKnowledgeService,
  evidence: evidenceAccess
}: AppDependencies) {
  const app = express();
  const clientDirectory = path.join(projectRoot, "dist");
  app.use(express.json({ limit: "1mb" }));
  app.use("/artifacts", express.static(path.join(runtimeDir(), "runs"), {
    fallthrough: false,
    immutable: true,
    maxAge: "1h"
  }));

  app.use("/research", express.static(evidenceResearchRoot(), {
    setHeaders: (response, filePath) => {
      // JSON data files are regenerated by analysis scripts; never serve stale copies.
      if (filePath.endsWith(".json")) response.setHeader("Cache-Control", "no-cache");
    }
  }));

  app.get("/api/health", (_request, response) => {
    response.json({ ok: true });
  });

  if (workflows) registerWorkflowRoutes(app, workflows);
  registerPublishingRoutes(app, publishingService);
  registerEvidenceRoutes(app, evidenceAccess);
  if (creatorResearchBatchService) registerCreatorResearchBatchRoutes(app, creatorResearchBatchService);
  registerWorkspaceRoutes(app, {
    creators: creatorResearchService, comparisons: comparisonProjectService,
    learningLoop: learningLoopControlPlane, knowledgeConcepts: () => contentKnowledgeService.listKnowledge(),
    publishing: publishingService, evidence: evidenceAccess
  });

  app.get("/api/creators", (_request, response) => {
    response.json({ creators: loadCreatorSummaries(creatorResearchService) });
  });

  app.get("/api/creator-runs", (request, response) => {
    const limit = Math.min(100, Math.max(1, Number(request.query.limit ?? 50)));
    response.json({ runs: creatorResearchService.list(limit) });
  });

  app.get("/api/creator-run-operations", (request, response) => {
    const limit = Math.min(100, Math.max(1, Number(request.query.limit ?? 50)));
    const runs = creatorResearchService.list(limit);
    const operations = buildCreatorRunOperations(runs, (run) => {
      const portfolio = creatorResearchService.portfolio(run.id);
      return {
        reconstructionBatch: portfolio?.reconstructionBatch ?? null,
        synthesisGate: portfolio?.synthesisGate ?? null,
        events: creatorResearchService.events(run.id),
        builderContractRevision: builderIntegrityContractRevision()
      };
    });
    response.json({ operations });
  });

  app.get("/api/creator-runs/:id", (request, response) => {
    const run = creatorResearchService.get(request.params.id);
    if (!run) return response.status(404).json({ error: "博主分析任务不存在" });
    return response.json(run);
  });

  app.get("/api/creator-runs/:id/events", (request, response) => {
    const run = creatorResearchService.get(request.params.id);
    if (!run) return response.status(404).json({ error: "博主分析任务不存在" });
    const after = Math.max(0, Number(request.query.after ?? 0));
    return response.json({ events: creatorResearchService.events(run.id, Number.isFinite(after) ? after : 0) });
  });

  app.get("/api/creator-runs/:id/events/stream", (request, response) => {
    const run = creatorResearchService.get(request.params.id);
    if (!run) return response.status(404).json({ error: "博主分析任务不存在" });
    response.setHeader("Content-Type", "text/event-stream");
    response.setHeader("Cache-Control", "no-cache, no-transform");
    response.setHeader("Connection", "keep-alive");
    response.flushHeaders();
    const existing = creatorResearchService.events(run.id, 0);
    let cursor = request.query.after === undefined
      ? existing.at(-1)?.sequence ?? 0
      : Math.max(0, Number(request.query.after));
    if (!Number.isFinite(cursor)) cursor = 0;
    const emit = () => {
      for (const event of creatorResearchService.events(run.id, cursor)) {
        cursor = event.sequence;
        response.write(`id: ${event.sequence}\n`);
        response.write("event: creator-research-event\n");
        response.write(`data: ${JSON.stringify(event)}\n\n`);
      }
      response.write(": keepalive\n\n");
    };
    emit();
    const timer = setInterval(emit, 1_500);
    request.once("close", () => clearInterval(timer));
    return undefined;
  });

  app.get("/api/creator-runs/:id/portfolio", (request, response) => {
    const portfolio = creatorResearchService.portfolio(request.params.id);
    if (!portfolio) return response.status(404).json({ error: "博主分析任务不存在" });
    return response.json(portfolio);
  });

  app.post("/api/creator-runs", (request, response) => {
    try {
      const input = createCreatorResearchRunInputSchema.parse(request.body);
      return response.status(202).json(creatorResearchService.create(input.profileUrl, input.adapter));
    } catch (error) {
      const message = error instanceof z.ZodError
        ? error.issues[0]?.message ?? "输入无效"
        : error instanceof Error ? error.message : "无法创建博主分析";
      return response.status(400).json({ error: message });
    }
  });

  app.post("/api/creator-discovery/redfox", async (request, response) => {
    try {
      const input = discoverCreatorsInputSchema.parse(request.body ?? {});
      const keywords = input.keywords ?? [...defaultAiCreatorKeywords];
      return response.json(await creatorDiscoveryService.discover({ ...input, keywords }));
    } catch (error) {
      const message = error instanceof z.ZodError
        ? error.issues[0]?.message ?? "发现参数无效"
        : error instanceof Error ? error.message : "无法发现 AI 博主";
      return response.status(400).json({ error: message });
    }
  });

  app.post("/api/creator-runs/:id/resume", (request, response) => {
    try {
      return response.status(202).json(creatorResearchService.resume(request.params.id));
    } catch (error) {
      const message = error instanceof Error ? error.message : "无法恢复博主分析";
      return response.status(message.includes("不存在") ? 404 : 409).json({ error: message });
    }
  });

  app.post("/api/creator-runs/:id/rebuild-selection", (request, response) => {
    try {
      return response.status(202).json(creatorResearchService.rebuildSelection(request.params.id));
    } catch (error) {
      const message = error instanceof Error ? error.message : "无法重算博主选样";
      return response.status(message.includes("不存在") ? 404 : 409).json({ error: message });
    }
  });

  app.post("/api/creator-runs/:id/retry-failed-videos", (request, response) => {
    try {
      return response.status(202).json(creatorResearchService.retryFailedReconstructions(
        request.params.id, builderIntegrityContractRevision()
      ));
    } catch (error) {
      const message = error instanceof Error ? error.message : "无法重试未通过视频";
      return response.status(message.includes("不存在") ? 404 : 409).json({ error: message });
    }
  });

  app.post("/api/creator-runs/:id/evaluate-videos", (request, response) => {
    try {
      const postExternalIds = z.array(z.string().min(1)).min(1).max(12).parse(request.body?.postExternalIds);
      return response.status(202).json(creatorResearchService.evaluateBuiltVideos(request.params.id, postExternalIds));
    } catch (error) {
      const message = error instanceof z.ZodError
        ? error.issues[0]?.message ?? "输入无效"
        : error instanceof Error ? error.message : "无法补做独立视频评估";
      return response.status(message.includes("不存在") ? 404 : 409).json({ error: message });
    }
  });

  app.post("/api/creator-runs/:id/continue-with-media-gaps", (request, response) => {
    try {
      return response.status(202).json(creatorResearchService.continueWithBoundedMediaGaps(request.params.id));
    } catch (error) {
      const message = error instanceof Error ? error.message : "无法在媒体缺口边界下继续研究";
      return response.status(message.includes("不存在") ? 404 : 409).json({ error: message });
    }
  });

  app.post("/api/creator-runs/:id/revalidate-synthesis", (request, response) => {
    try {
      return response.status(202).json(creatorResearchService.revalidateSynthesis(request.params.id));
    } catch (error) {
      const message = error instanceof Error ? error.message : "无法重验博主综合";
      return response.status(message.includes("不存在") ? 404 : 409).json({ error: message });
    }
  });

  app.post("/api/creator-runs/:id/resynthesize", (request, response) => {
    try {
      return response.status(202).json(creatorResearchService.resynthesize(request.params.id));
    } catch (error) {
      const message = error instanceof Error ? error.message : "无法重新生成博主综合";
      return response.status(message.includes("不存在") ? 404 : 409).json({ error: message });
    }
  });

  app.post("/api/creator-runs/:id/portfolio-annotations/rebuild", (request, response) => {
    try {
      const resynthesize = request.body?.resynthesize !== false;
      return response.status(202).json(creatorResearchService.annotatePortfolio(request.params.id, resynthesize));
    } catch (error) {
      const message = error instanceof Error ? error.message : "无法生成全量作品表层标注";
      return response.status(message.includes("不存在") ? 404 : 409).json({ error: message });
    }
  });

  const listComparisons: express.RequestHandler = (request, response) => {
    const limit = Math.min(100, Math.max(1, Number(request.query.limit ?? 50)));
    response.json({ projects: comparisonProjectService.list(limit) });
  };

  const getComparison: express.RequestHandler = (request, response) => {
    const rawId = request.params.id;
    const id = Array.isArray(rawId) ? rawId[0] : rawId;
    if (!id) return response.status(400).json({ error: "多博主比较项目 ID 无效" });
    const project = comparisonProjectService.get(id);
    if (!project) return response.status(404).json({ error: "多博主比较项目不存在" });
    return response.json(project);
  };

  const createComparison: express.RequestHandler = (request, response) => {
    try {
      return response.status(202).json(comparisonProjectService.create(request.body));
    } catch (error) {
      const message = error instanceof z.ZodError
        ? error.issues[0]?.message ?? "输入无效"
        : error instanceof Error ? error.message : "无法创建多博主比较";
      return response.status(400).json({ error: message });
    }
  };

  app.get("/api/comparison-projects", listComparisons);
  app.get("/api/comparison-projects/:id", getComparison);
  app.post("/api/comparison-projects", createComparison);
  app.get("/api/v1/comparisons", listComparisons);
  app.get("/api/v1/comparisons/:id", getComparison);
  app.get("/api/v1/comparisons/:id/dossier", (request, response) => {
    const dossier = loadComparisonDossier(comparisonProjectService, creatorResearchService, request.params.id);
    if (!dossier) return response.status(404).json({ error: "多博主研究项目不存在" });
    return response.json(dossier);
  });
  app.post("/api/v1/comparisons", createComparison);

  app.get("/api/v1/creators/:id", (request, response) => {
    const dossier = loadCreatorDossier(creatorResearchService, request.params.id);
    if (!dossier) return response.status(404).json({ error: "博主研究档案不存在" });
    return response.json(dossier);
  });

  app.get("/api/v1/creators/:id/videos/:videoId", (request, response) => {
    const requestedRunId = typeof request.query.run === "string" ? request.query.run : undefined;
    const evidence = loadVideoResearch(creatorResearchService, request.params.id, request.params.videoId, requestedRunId);
    if (!evidence) return response.status(404).json({ error: "视频研究证据不存在" });
    return response.json(evidence);
  });

  app.get("/api/v1/video-research/latest", (_request, response) => {
    return response.json({ items: listLatestVideoResearch(creatorResearchService) });
  });

  app.get("/api/v1/research-concepts", (_request, response) => {
    return response.json({ concepts: researchLearningService.list() });
  });

  app.post("/api/v1/research-analysis-revisions", (request, response) => {
    try {
      const input = ingestAnalysisRevisionSchema.parse(request.body);
      return response.status(201).json(researchLearningService.ingestAnalysisRevision(input));
    } catch (error) {
      const message = error instanceof z.ZodError
        ? error.issues[0]?.message ?? "认知观察输入无效"
        : error instanceof Error ? error.message : "无法沉淀认知观察";
      return response.status(400).json({ error: message });
    }
  });

  app.get("/api/v1/research-concepts/:id", (request, response) => {
    const concept = researchLearningService.get(request.params.id);
    if (!concept) return response.status(404).json({ error: "研究概念不存在" });
    return response.json(concept);
  });

  registerKnowledgeActivationRoutes(app, new KnowledgeActivationService(creatorResearchService,
    comparisonProjectService, contentKnowledgeService));
  registerKnowledgeRoutes(app, contentKnowledgeService, publishingService);

  registerLearningLoopRoutes(app, learningLoopControlPlane);

  const retiredSinglePost = (_request: express.Request, response: express.Response) => response.status(410).json({
    error: "旧单帖分析接口已停用；请从当前博主研究批次读取 builderLenses 报告。",
    code: "LEGACY_SINGLE_POST_RETIRED"
  });
  app.get("/api/runs", retiredSinglePost);
  app.get("/api/runs/:id", retiredSinglePost);
  app.post("/api/runs", retiredSinglePost);
  app.post("/api/runs/:id/retry", retiredSinglePost);

  registerSpaFallback(app, clientDirectory);

  app.use((error: unknown, _request: express.Request, response: express.Response, _next: express.NextFunction) => {
    void _next;
    const message = error instanceof Error ? error.message : "服务异常";
    response.status(500).json({ error: message });
  });
  return app;
}
