import { AlertTriangle, ArrowRight, ExternalLink, LoaderCircle, RefreshCw } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import type { CreatorResearchRun, CreatorRunOperation, CreatorRunOperationAction } from "../../../shared/contracts/core";
import { creatorRecoveryPresentation } from "../model/creator-recovery";
import { creatorStatusLabels, taskPhases } from "../model/creator-task-state";

const filters = ["all", "active", "attention", "ready"] as const; type Filter = typeof filters[number];
function fits(run: CreatorResearchRun, filter: Filter) { if (filter === "all") return true; if (filter === "ready") return run.status === "ready"; if (filter === "attention") return ["needs_user", "backoff", "failed", "reviewable", "stale"].includes(run.status); return !["ready", "needs_user", "backoff", "failed", "reviewable", "stale"].includes(run.status); }
export function ResearchLibraryProgress({ runs, operations, loading, error, operatingId, onOperate, onRefresh }: { runs: CreatorResearchRun[] | null; operations: CreatorRunOperation[] | null; loading: boolean; error: string | null; operatingId: string | null; onOperate: (id: string, action: CreatorRunOperationAction) => Promise<void>; onRefresh: () => Promise<void> }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState<Filter>("all");
  const byRun = useMemo(() => new Map((operations ?? []).map((item) => [item.runId, item])), [operations]);
  const filtered = useMemo(() => (runs ?? []).filter((run) => fits(run, filter) && `${run.creatorName ?? ""} ${run.profileUrl}`.toLowerCase().includes(query.toLowerCase())), [runs, filter, query]);
  const counts = useMemo(() => ({ all: runs?.length ?? 0, active: (runs ?? []).filter((run) => fits(run, "active")).length, attention: (runs ?? []).filter((run) => fits(run, "attention")).length, ready: (runs ?? []).filter((run) => run.status === "ready").length }), [runs]);
  const labels = { all: "全部", active: "进行中", attention: "需关注", ready: "已完成" };
  return <section className="research-library__content" aria-labelledby="creator-progress-title"><div className="research-library__bar"><div><h2 id="creator-progress-title">分析进度 <b>{counts.all}</b></h2><p>每个链接对应一个独立任务；恢复操作只作用于该任务。</p></div><button type="button" className="research-refresh" onClick={() => void onRefresh()}><RefreshCw size={14}/>刷新</button></div><div className="research-progress-tools"><div className="research-filter" role="group" aria-label="按状态筛选">{filters.map((item) => <button type="button" key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{labels[item]}<b>{counts[item]}</b></button>)}</div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索名称或主页链接"/></div>{error && <p className="research-error"><AlertTriangle size={15}/>{error}</p>}{loading && runs === null ? <div className="research-empty">正在读取分析进度…</div> : filtered.length > 0 ? <div className="research-run-list">{filtered.map((run) => <RunCard key={run.id} run={run} operation={byRun.get(run.id)} busy={operatingId === run.id} onOperate={onOperate}/>)}</div> : <div className="research-empty">没有符合当前筛选条件的任务。</div>}</section>;
}
function RunCard({ run, operation, busy, onOperate }: { run: CreatorResearchRun; operation?: CreatorRunOperation; busy: boolean; onOperate: (id: string, action: CreatorRunOperationAction) => Promise<void> }) { const current = run.stages.find((stage) => stage.id === run.currentStage); const recovery = creatorRecoveryPresentation(run, operation ?? null); const href = `/creators/${encodeURIComponent(run.canonicalSlug ?? run.creatorId ?? run.id)}?run=${encodeURIComponent(run.id)}`; return <article className={`research-run-card research-run-card--${run.status}`}><div className="research-run-card__identity"><span className={`research-status research-status--${run.status}`}>{creatorStatusLabels[run.status]}</span><h3>{run.creatorName ?? "待识别博主"}</h3><a href={run.profileUrl} target="_blank" rel="noreferrer">主页 <ExternalLink size={12}/></a></div><div className="research-run-card__work"><strong>{current?.label ?? "等待预检"}</strong><p>{run.nextAction}</p><div className="research-phase" aria-label="研究阶段">{taskPhases(run).map((phase) => <i key={phase.id} className={`is-${phase.state}`} title={`${phase.label}：${phase.detail}`}/>)}</div></div><div className="research-run-card__coverage"><span><b>{operation?.coverage.discovered ?? run.coverage.discoveredPosts}</b>发现</span><span><b>{operation ? `${operation.coverage.enriched}/${operation.coverage.enrichedTarget}` : run.coverage.enrichedPosts}</b>详情</span><span><b>{operation ? `${operation.coverage.reconstructed}/${operation.coverage.reconstructedTarget}` : run.coverage.reconstructedPosts}</b>重建</span></div><div className="research-run-card__actions">{recovery && <button type="button" disabled={busy} onClick={() => void onOperate(run.id, recovery.action)}>{busy ? <LoaderCircle className="spin" size={13}/> : <RefreshCw size={13}/>}{recovery.label}</button>}<Link to={href}>{run.status === "ready" ? "打开档案" : "查看任务"}<ArrowRight size={14}/></Link></div></article>; }
