import { ExternalLink, Search, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import type { CreatorResearchRun, CreatorSummary } from "../../../shared/contracts/core";

export function ResearchLibraryCatalog({ creators, runs, loading }: { creators: CreatorSummary[] | null; runs: CreatorResearchRun[] | null; loading: boolean }) {
  const [query, setQuery] = useState("");
  const cards = useMemo(() => (creators ?? []).filter((creator) => `${creator.name} ${creator.positioning} ${creator.tags.join(" ")}`.toLowerCase().includes(query.trim().toLowerCase())), [creators, query]);
  const inProgress = (runs ?? []).filter((run) => !["ready", "reviewable", "failed", "needs_user", "stale", "backoff"].includes(run.status)).length;
  return <section className="research-library__content" aria-labelledby="creator-library-title"><div className="research-library__bar"><div><h2 id="creator-library-title">我的博主 <b>{creators?.length ?? 0}</b></h2><p>{inProgress ? `${inProgress} 个任务正在进行，进度在“分析进度”查看。` : "已完成的研究档案会保存在这里。"}</p></div><label className="research-search"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索名称、定位或标签"/></label></div>{loading && creators === null ? <div className="research-empty">正在读取研究库…</div> : cards.length > 0 ? <div className="research-creator-grid">{cards.map((creator) => { const current = creator.entries[0]; return <article className="research-creator-card" key={creator.id}><div className="research-creator-card__title"><div><h3>{creator.name}</h3><p>{creator.positioning}</p></div><a href={creator.profileUrl} target="_blank" rel="noreferrer" aria-label={`打开 ${creator.name} 主页`}><ExternalLink size={15}/></a></div><p className="research-creator-card__summary">{creator.summary}</p><div className="research-creator-card__stats"><span><b>{creator.followers}</b>粉丝</span><span><b>{creator.likesAndCollections}</b>赞藏</span></div><div className="research-creator-card__tags">{creator.tags.slice(0, 4).map((tag) => <span key={tag}>{tag}</span>)}</div><Link to={current?.href ?? `/creators/${encodeURIComponent(creator.id)}`}>{current?.label ?? "打开研究档案"}</Link></article>; })}</div> : <div className="research-empty"><UserRound size={20}/>{query ? "没有匹配的博主。" : "还没有完成的博主档案。"}</div>}</section>;
}
